config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  get 'users/:user_id/friends/candidate' => 'friends#candidate'

  resources :users do
    resources :debts
    resources :friends
    resources :expenses
    resources :purchases
  end

  resources :sessions, only: [:new, :create, :destroy]

  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:user_id/debts/:id/pay' => 'debts#pay'
  get 'users/:user_id/expenses/:id/pay' => 'expenses#pay'
  get 'users/:user_id/purchases/:id/pay' => 'purchases#pay'

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'settings' => 'settings#edit'
  post 'settings/update' => 'settings#update'

  post 'users/:user_id/friends/add/:friend_id' => 'friends#add'

  get 'admin/reports' => 'reports#index'

end

app/models/debt.rb
class Debt
  field :title,   type: String
  field :amount,  type: Integer
  field :paid,    type: Boolean, default: false

  validates :amount, presence: true, numericality: true
  validates :title, presence: true
  validates :owner_id, presence: true

  def self.user_debts(user_id)
    Debt.select{ |debt| debt.user_id == user_id && debt.paid == false }
  end

  def self.owner_debts(owner_id)
    Debt.select{ |debt| debt.owner_id == owner_id && debt.paid == false }
  end

end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :set_debt, only: [:show, :edit, :update, :pay, :destroy]
  before_action :set_user, only: [:new, :update, :index, :edit, :create]
  before_action :set_users, only: [:new, :edit, :create, :update]

  # GET /debts
  def index
    @debts = Debt.user_debts(current_user.id)
  end

  # GET /debts/1
  def show
  end

  # GET /debts/new
  def new
    @debt = Debt.new
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts
  def create
    @debt = Debt.new(debt_params)
    @debt.user_id = params.require :user_id
    @debt.paid = false
    if @debt.save
      if @debt.owner.settings['email_notification_enabled'] && @debt.owner.settings['email_notification_frecuency'] == 'instantly'

        I18n.locale = @debt.owner.settings['language']
        UserMailer.instant_email(@debt.owner_id, @debt).deliver_later unless @debt.owner_id == current_user.id

      end

      redirect_to user_debts_path(params.require :user_id), notice: t('was_successfully_created_f',name: t('debt'))
    else
      render :new
    end
  end

  # PATCH/PUT /debts/1
  def update
      if @debt.update(debt_params)
        redirect_to user_debts_url, notice: t('was_successfully_updated_f', name: t('debt'))
      else
        render :edit
      end
  end

  # GET /debts/1/pay
  def pay
    @debt.paid = true
    if @debt.save
      redirect_to user_debts_url, notice: t('was_marked_as_paid_f', name: t('debt'))
    else
      redirect_to user_debts_url, error: t('was_not_marked_as_paid_f', name: t('debt'))
    end
  end

  # DELETE /debts/1
  def destroy
    @debt.destroy
    redirect_to user_debts_url, notice: t('was_successfully_destroyed_f', name: t('debt'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debt_params
      params.require(:debt).permit(:title, :amount, :owner_id)
    end

    def set_user
      @user = User.find(params.require :user_id)
    end

    def set_users
      @users = @user.current_friends.pluck(:name, :id)
    end
end

app/helpers/debts_helper.rb
module DebtsHelper
  def pay_user_debt_path debt
    "/users/#{@user.id}/debts/#{debt.id}/pay/"
  end
end

app/views/debts/_form.html.erb
<%= form_for([@user,@debt], url: { action: action } ) do |f| %>
<% if @debt.errors.any? %>
<div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h2><%= pluralize(@debt.errors.count, "error") %> prohibited this debt from being saved:</h2>
    <ul>
    <% @debt.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <%= notice %>
</div>
<script type="text/javascript">
  $( document ).ready(function()
  {
    $('.field_with_errors').css ("display","block");
    $('.field_with_errors').css ("background-color","#eee");
    $('.field_with_errors').css ("border-radius","3px");
  });
</script>
<% end %>

<div class="col-lg-6">
  <div class="well bs-component">
    <form class="form-horizontal">
      <fieldset>
        <legend></legend>

        <div class="form-group">
          <%= f.label t(:title), class:'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_field :title, class:'form-control', placeholder: t(:title), required: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t(:amount), class:'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_field :amount, class:'form-control', placeholder: t(:amount), required: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t(:owner), class:'col-lg-2 control-label'  %>
          <div class="col-lg-10">
            <%= f.select :owner_id, @users, {}, { class: "form-control", required: true } %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= link_to t(:cancel), user_debts_path, class:"btn btn-default" %>
            <button type="submit" class="btn btn-primary"><%= t(:submit) %></button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
<% end %>

app/views/debts/edit.html.erb
<div class="col-lg-12">
  <h1><%= t('editing_debt') %></h1>
</div>
<%= render 'form', action: 'update' %>

app/views/debts/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="col-lg-12">
  <h1 id="tables"><%= t('listing_debts_you_created') %></h1>

  <div class="bs-component">
    <table class="table table-striped table-hover ">

      <thead>
        <tr>
          <th><%= t('title') %></th>
          <th><%= t('amount') %></th>
          <th><%= t('debt_owner') %></th>
          <th><%= t('issue_date') %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @debts.each do |debt| %>
          <tr>
            <td><%= debt.title %></td>
            <td><%= debt.amount %></td>
            <td><%= debt.owner.name %></td>
            <td><%= debt.created_at.strftime("%d/%m/%Y %H:%M hs") %></td>
            <td><%= link_to t('mark_as_paid'), pay_user_debt_path(debt) %></td>
            <td><%= link_to t('edit'), edit_user_debt_path(@user,debt) %></td>
            <td><%= link_to t('destroy'), user_debt_path(@user,debt), method: :delete, data: { confirm: t('are_you_sure') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to t('new_debt'), new_user_debt_path, class:"btn btn-primary" %>
</div>

app/views/debts/new.html.erb
<div class="col-lg-12">
  <h1><%= t('new_debt') %></h1>
</div>
<%= render 'form', action: 'create' %>

app/views/debts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @debt.title %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @debt.amount %>
</p>

<%= link_to 'Edit', edit_user_debt_path(@debt) %> |
<%= link_to 'Back', user_debts_path %>