config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  get 'users/:user_id/friends/candidate' => 'friends#candidate'

  resources :users do
    resources :debts
    resources :friends
    resources :expenses
    resources :purchases
  end

  resources :sessions, only: [:new, :create, :destroy]

  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:user_id/debts/:id/pay' => 'debts#pay'
  get 'users/:user_id/expenses/:id/pay' => 'expenses#pay'
  get 'users/:user_id/purchases/:id/pay' => 'purchases#pay'

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'settings' => 'settings#edit'
  post 'settings/update' => 'settings#update'

  post 'users/:user_id/friends/add/:friend_id' => 'friends#add'

  get 'admin/reports' => 'reports#index'

end

app/models/friend.rb
class Friend < User
    def self.candidate_friends(user)
        candidate_users = (User.current_users.pluck(:id) - user.friends.pluck(:id)).reject{ |id| id == user.id }
        Friend.select { |friend| candidate_users.include?(friend.id) }
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_candidate_friends

  # GET /users/1/friends
  def index
  end

  # GET /users/1/friends/candidate
  def candidate
    clue = params[:clue]
    @candidate_friends = @candidate_friends.select { |friend| friend.name.include?(clue) || friend.email.include?(clue) }
    render :layout => false
  end

  # POST /users/1/friends/add
  def add
    @user.friends << Friend.find(params[:friend_id])
    if @user.save
      redirect_to user_friends_path(@user.id), notice: t('was_successfully_added',name: t('friend'))
    else
      render :new, notice: t('was_not_successfully_added',name: t('friend'))
    end
  end

  # DELETE /users/1/friends
  def destroy
    @user.friends.delete(Friend.find(params[:id]))
    redirect_to user_friends_url, notice: t('was_successfully_destroyed_m', name: t('friend'))
  end

  private

  def set_user
    @user = User.find(params.require :user_id)
  end

  def set_candidate_friends
    @candidate_friends = Friend.candidate_friends(@user)
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
  def add_friend_path friend
    "/users/#{@user.id}/friends/add/#{friend.id}"
  end
end

app/views/friends/_friends_table.html.erb
<table id="friends_table" class="table table-striped table-hover ">
  <thead>
    <tr>
      <th><%= t('name') %></th>
      <th><%= t('email') %></th>
      <th><%= t('image') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.email %></td>
        <td><% unless friend.image.nil? %><img src="<%= friend.image %>" class="friend_image"><% end %></td>
        <% if candidate == true %>
          <td><%= link_to t('add_friend'), add_friend_path(friend), method: :post %></td>
        <% else %>
          <td><%= link_to t('delete_friend'), user_friend_path(@user,friend), method: :delete, data: { confirm: t('are_you_sure') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/candidate.erb
<%= render 'friends_table', friends: @candidate_friends, candidate: true %>

app/views/friends/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>
<div class="container-fluid">
  <div class="row">
    <div class="form-horizontal">
      <div class="col-lg-4">
        <div class="well bs-component">
          <div class="form-group">
            <label class="col-lg-4 control-label" for="friend_identification"><%= t('search_friend') %></label>

            <div class="col-lg-7">
              <input class="form-control ui-autocomplete-input" type="text" id="friend_identification" autocomplete="off">
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-lg-6">
   <h1 id="tables"><%= t('cantidate_friends') %></h1>

  <div class="bs-component">
    <%= render 'friends_table', friends: @candidate_friends, candidate:true %>
  </div>
</div>

<div class="col-lg-6">
   <h1 id="tables"><%= t('current_friends') %></h1>

  <div class="bs-component">
    <%= render 'friends_table', friends: @user.friends, candidate: false %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('#friend_identification').on('change input autocompleteselect',function(event, ui){
      get_friends('/users/<%= @user.id %>/friends/candidate','clue='+$(this).val());
    });

  });
  function get_friends(url,data)
  {
    $.get(url,data,function(data){$('#friends_table').html(data)});
  }
</script>