config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  get 'users/:user_id/friends/candidate' => 'friends#candidate'

  resources :users do
    resources :debts
    resources :friends
    resources :expenses
    resources :purchases
  end

  resources :sessions, only: [:new, :create, :destroy]

  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:user_id/debts/:id/pay' => 'debts#pay'
  get 'users/:user_id/expenses/:id/pay' => 'expenses#pay'
  get 'users/:user_id/purchases/:id/pay' => 'purchases#pay'

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'settings' => 'settings#edit'
  post 'settings/update' => 'settings#update'

  post 'users/:user_id/friends/add/:friend_id' => 'friends#add'

  get 'admin/reports' => 'reports#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= ENV['APP_NAME'] %></title>
      <link rel="apple-touch-icon" href="<%= asset_path('apple-touch-icon-precomposed.png') %>" />
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <body>
    <div class="navbar noMargin">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-warning-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="version: <%= ENV["APP_VERSION"] %>"><img class="dues-logo" src="/assets/dues_logo.png"></a>
        </div>
        <div class="navbar-collapse collapse navbar-warning-collapse">
            <ul class="nav navbar-nav">
            <% if current_user != nil %>
                <li id="debts">
                    <%= link_to t('debts'), user_debts_path(current_user.id) %>
                </li>
                <li id="purchases">
                    <%= link_to t('purchases'), user_purchases_path(current_user.id) %>
                </li>
                <li id="expenses">
                    <%= link_to t('expenses'), user_expenses_path(current_user.id) %>
                </li>
                <li id="friends">
                    <%= link_to t('friends'), user_friends_path(current_user.id) %>
                </li>
                <% if !current_user.nil? && current_user.admin? %>
                <li id="reports">
                    <%= link_to t('reports'), admin_reports_path(current_user.id) %>
                </li>
                <% end %>
                <li id="settings">
                    <%= link_to t('settings'), settings_path %>
                </li>
            <% end %>
            </ul>

            <ul class="nav navbar-nav navbar-right dropdown">
                <% if current_user != nil %>
                <li>
                    <a class="user_name" href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                        <div class="user_name_label">
                            <%= t('hello', name: current_user.name) %>
                        </div>
                        <% if current_user.image != nil %>
                            <img src="<%= current_user.image %>" class="facebook-image" >
                        <% end %>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to t('logout'), '/logout', :method => :delete %></li>
                    </ul>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
    <%= yield %>

    <script>
        $(function() {
            $.material.init();
            $('#<%= controller_name %>').addClass("active")
        });
    </script>

    </body>
</html>